export {
    default,
    DEFAULT_THEME,
    themeToCssVars,
    getErrorMessage,
    getActiveProducts,
    getProductById,
    searchProductsByName,
    searchProductsByPrice,
    searchProductsByRating,
    extractCategories,
    applyClientFilters,
    loadCatalogProducts,
    registerUser,
    loginUser,
} from "../api.js";
